package pl.justyna.HelloBunnies.config;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import pl.justyna.HelloBunnies.model.FirstBunny;
import pl.justyna.HelloBunnies.service.FirstBunnyService;

@Configuration
public class FirstBunnyDataInitializeConfig {

	@Autowired
	private FirstBunnyService firstBunnyService;

	@Bean
	public InitializingBean insertFirstBunnyInitialData() {
		return () -> {

			firstBunnyService.create(new FirstBunny("Dziecko i królik, czy to dobre rozwiązanie?",
					"Jednoznaczna odpowiedź na to pytanie jest niemożliwa, ponieważ to czy dziecko będzie dobrym opiekunem dla królika zależy od wielu czynników. Kilka z nich to: wiek dziecka, poczucie obowiązku i odpowiedzialności, nasz wpływ na zachowanie dziecka, naszą chęć pomocy przy opiece (niezbędny czynnik) i jeden z najważniejszych, nie wychowywać dziecka kosztem królika.</br>"
							+ "</br>"
							+ "Przed zakupem/adopcją królika dla dziecka musimy sobie uzmysłowić kilka podstawowych kwestii odnośnie królika. Na ich temat w internecie i w naszej świadomości krąży szereg stereotypów i mitów nie mających odzwierciedlenia w rzeczywistości. Większości wydaje się że są to zwierzęta spokojne, kochane, idealne do przytulania i zabaw z nimi lub nimi.</br>"
							+ "</br>"
							+ "Powinniśmy wiedzieć, że królik świat poznaje poprzez gryzienie, to mebli, to listew przypodłogowych, progów itp., są częstymi bywalcami za źle zabezpieczonymi szafami, pod segmentami i wersalkami. Dzieje się tak gdy króliki biegają \"luzem\" po domu, więc pewnie po przeczytaniu tego fragmentu, rodzic stwierdzi że królika zamkną w klatce, co jest bardzo złym rozwiązaniem, które ma wpływ na zdrowie i szybszą śmierć królika. Króliki są również bardzo delikatnymi zwierzętami fizycznie, to oznacza że dzieci przy \"zabawie\" mogą zrobić im krzywdę uszkadzając organy wewnętrzne, zresztą nie każdy królik lubi zabawy, a już na pewno błędem jest myślenie, że z królikiem będziemy bawić się tak jak z psem. Zazwyczaj branie uszatego pupila wiąże się dla niego ze stresem, stąd częste podrapania i wyrywanie zwierzęcia, takie zachowanie bierze się z instynktownego poczucia, że gdy jest brane na ręce, czyli podnoszone do góry, to tak jakby był porywany przez drapieżnego ptaka, więc gdy królik reaguje na to strachem i agresją, nie warto narażać go na takie doznania. Króliki swoje zalety pokazują dopiero gdy zostawimy je w spokoju, co zazwyczaj zniechęca dzieci. Królik lubi się bawić, ale na własnych zasadach, tzn. że jeżeli straci zainteresowanie zabawą, nie ma ochoty lub wypatrzył inne zajęcie to zabawa dziecka się kończy i żadne zmuszanie nie przekona uszaka do powrotu. Jak już wcześniej zostało wspomniane, króliki swoje prawdziwe oblicze pokazują, gdy zostawimy je w spokoju i skupimy się na obserwacji, wtedy możemy zauważyć szereg ciekawych zachowań, które potęgują doznania w chwili gdy królik jest trzymany ze współtowarzyszem.</br>"
							+ "</br>" + "Atutami królika są:</br>"
							+ " - mogą być bardzo zabawne i śmieszne gdy na nie patrzymy, bez ingerencji;</br>"
							+ " - stosunkowo potrzebują mniej miejsca w domu niż pies czy kot;</br>"
							+ " - potrafią nawiązać bardzo silną więź z człowiekiem.</br>" + "</br>"
							+ "Króliki są zwierzętami społecznymi, co oznacza, że do prawidłowego funkcjonowania potrzebują współtowarzysza w postaci drugiego królika, najlepszym połączeniem jest samica + wykastrowany samiec. Aby współżycie dziecka i królika odbywało się w poprawnych stosunkach należy uzmysłowić z natury niecierpliwemu dziecku, że przymusem, krzykiem i nie daj Boże biciem nic nie wskóramy u tego zwierzęcia, na takie zachowanie dziecka królik będzie reagować ucieczką i tupaniem. Podstawą nawiązania przyjaźni z królikiem jest zdobycie jego zaufania, które wiąże się z duża cierpliwością z naszej strony, jak również dziecka.</br>"
							+ "</br>"
							+ "Królik jako zwierze potrzebujące dużo ruchu powinno jak największą część dnia spędzać poza klatką, więc gdy dziecko straci zainteresowanie odpowiedzialność pilnowania królika spada na jego rodziców.</br>"
							+ "</br>"
							+ "W okresie dojrzewania i rujki królik może zmienić swoje zachowanie. Z grzecznego i ładnie korzystającego z kuwety królika może z dnia na dzień powstać mała bestyjka, która przy każdej próbie włożenia ręki do klatki warczy i próbuje ugryźć w palec, bzyczy i gania dookoła nóg, znaczy teren obsikując właściciela, przedmioty, pościel, ściany itd. oraz zostawia masę bobków na podłodze i łóżku. Jednak nie powinniśmy się tym zrażać jest to okres przejściowy i wiąże się z młodzieńczym buntem i dorastaniem</br>"
							+ "</br>"
							+ "Więc dziecko wraz z królikiem ma szansę powodzenia, tylko i wyłącznie przy pomocy osób dorosłych, ustaleniu stały, rozsądnych (dla królika) i niezmiennych zasad, warto również brać pod uwagę fakt że króliki potrafią dożyć do 13 lat, więc jest to zobowiązanie na lata, w trakcie których sytuacja dziecka (nowe szkoły, wyjazdy itp.) mogą ulec zmianie i to należy także brać pod uwagę.</br>"
							+ ""));

			firstBunnyService.create(new FirstBunny("Zanim adoptujesz/kupisz królika",
					"Jak to zazwyczaj bywa, w przypadku wzięcia zwierzęcia dla dziecka, końcowa odpowiedzialność opieki spada na rodziców. To właśnie głównie na dorosłych będzie obowiązek zdobywania wiedzy na różnego rodzaju tematy.</br>"
							+ "</br>"
							+ "Ważne jest aby przed zakupem/adopcją królika zdobyć podstawy wiedzy na temat tych przemiłych stworzeń. Są to zwierzęta, które bardzo źle znoszą zmiany, szczególnie zmiany żywieniowe i właśnie od diety powinniśmy zacząć poznawać te zwierzęta, to najważniejszy aspekt przy ich opiece. Rodzic musi sobie uzmysłowić, że króliki są niebywale delikatnymi zwierzętami, wrażliwymi na stres i nieodpowiednią dietę. Objawy wszelkich chorób są bardzo subtelne i dużym atutem opiekuna jest ich znajomość i umiejętność szybkiej reakcji. Króliki to zwierzęta dość łatwo zapadające na choroby, więc dużo rozsądniejsze jest zapobieganie ich, niż ewentualne leczenie, które może by długotrwałe i kosztowne. Istotne są również regularne szczepienia.</br>"
							+ "</br>"
							+ "Przed podjęciem się opieki nad królikiem, należy (co było już wspomniane w temacie \"królik i dziecko\") wziąć pod uwagę wiek życia królika, czyli nie może być sytuacji, że po kilku miesiącach/latach nasza sytuacja na tyle się zmieni że królika albo oddamy do schroniska, albo porzucimy w \"ustronnym miejscu\".</br>"
							+ "</br>"
							+ "Niezmiernie ważna jest również cierpliwość, szczególnie na początku, przy nauce korzystania z toalety i oswojenie się z naturą królika. Królik potrzebuje również, aby człowiek poświęcał mu sporo czasu, przez co wytwarza się silna więź, która wynagrodzi nam poświęcony czas. Wiedza odnośnie zdrowia królika, nie sprowadza się tylko do prawidłowej diety, ale również do \"przestrzeni życiowej\", jeżeli nie możemy sobie pozwolić na trzymanie królika wolno biegającego po pokoju (wychowanie bezklatkowe), to dziennie musimy mu zapewnić co najmniej 4 godziny swobodnego biegania poza klatką, ma to ogromny wpływ na prawidłowy rozwój kości i ogólną kondycję. W związku z wypuszczaniem królika, lub właśnie \"wychowaniem bezklatkowym\" musimy się liczyć z tym że królik pomimo że sam jest wielkim czyściochem to jego otoczeniu już niekoniecznie, więc na nas spadnie obowiązek sprzątania ewentualnych bobków, podartych gazet itp. Jak już jesteśmy przy gazetach, to nie sposób nie wspomnieć o zabawkach, które są istotne w życiu królik.  Nudzący się królik, to chodzący niszczyciel, więc warto pomyśleć o zagospodarowaniu czasu naszemu pupilowi (rodzaje zabawek są opisane w dziale królicze zabawki), ale nie popadajmy w paranoję i nie wychodźmy z założenia, że królik wolno biegający to tylko zniszczenia, po prostu poznając dobrze naturę królika, w dość łatwy sposób jesteśmy wstanie zminimalizować szkody, które może wyrządzić uszak. Wpływ na zachowanie ma również wiek królika i to jak się z nim obchodzimy, nie możemy w żadnej sytuacji pozwolić sobie na krzyk i bicie, takie praktyki odniosą odwrotny efekt od zamierzonego i również zniszczą naszą więź z królikiem, nie wspominając o zaufaniu zwierzęcia do nas. Również wiek dziecka i usposobienie nie jest bez znaczenia, mianowicie króliki zdecydowanie są odradzane dzieciom poniżej 7 roku życia, gdyż dzieci w takim wieku są zazwyczaj hałaśliwe, również ważne jest jak dziecko jest usposobione, czy jest agresywne, czy jest (nadal) bardzo hałaśliwe, lubiące ruch itp. Króliki to spokojne zwierzęta, które nie lubią w swoim otoczeniu nadmiernego hałasu, szybkiego ruchu, to je bardzo stresuje i w takich sytuacjach bardzo łatwo o paniczne zachowanie, które odbija się na naszych stosunkach z uszakiem. Dlatego też ustawienie klatki powinno być na tyle rozsądne, aby nie stało blisko urządzeń, takich jak TV, wieża grająca, ale również nie była odosobniona i abyśmy mieli kontakt wzrokowy z nią.</br>"
							+ "</br>"
							+ "Koszty początkowe przy zakupie królika, są tak naprawdę kroplą w morzu późniejszych wydatków. Po zakupie niezbędnych rzeczy takich jak: duża klatka, poidełka, kuwet, podłoże itp., do kolejnych wydatków dojdzie odpowiednie pożywienie, wszelkiego rodzaju przyrządy ułatwiające pielęgnację, ewentualne leki itp. Więc przy zakupie królika nie liczmy ile nas to wyniesie na początku, ale policzmy czy będzie nas stać na późniejszą opiekę, na której naprawdę nie warto oszczędzać, bo koszty leczenia są zdecydowanie wyższe.</br>"
							+ "</br>"
							+ "Na początku przygody z królikiem, ważne jest również zwrócenie uwagi na ewentualne alergie naszych domowników, aby potem nie było sytuacji, że \"oddaje królika bo dziecko ma alergie\" takie rzeczy musimy sprawdzać wcześniej, bo królik to nie przedmiot, bardzo przeżywa rozstania z opiekunami, źle znosi brak zainteresowania i wyczuwa naszą niechęć do siebie.</br>"
							+ "</br>"
							+ "Więc rodzicu zanim zdecydujesz się na królika w domu, bardzo poważnie przemyśl decyzję, wybiegając w przyszłość. Artykuł wyżej nie ma zniechęcać do tych kochanych zwierząt, ale pokazać że kupno królika wiąże się ze zdobyciem ogromu wiedzy, ale gwarantuję że wszystkie nasze starania zostaną wielokrotnie wynagrodzone!</br>"
							+ ""));

			firstBunnyService.create(new FirstBunny("Trzymanie królików zgodnie z ich naturą w mieszkaniu",
					" Trzymanie królików zgodnie z naturą w mieszkaniu? To stwierdzenie jest jednocześnie zaprzeczeniem, ponieważ w większości mieszkań króliki nie mają możliwości zgodnie z naturalną potrzebą np. kopać w podłożu. Większość opiekunów pragnie trzymać swoje króliki u siebie w mieszkaniu, lub na balkonie, aby mieć z nimi ścisły kontakt. Oczywiście można także w mieszkaniu stworzyć królikowi warunki jak najbardziej zbliżone do naturalnych. Jest to powiązane z dużym nakładem pracy i zrozumieniem, liczeniem się z królikiem.</br>"
							+ "</br>" + "Jak powinna wyglądać zagródka?</br>"
							+ "Jaka nie powinna być można zobaczyć w sklepach zoologicznych i u wielu opiekunów. Mała klatka dla 1-2 królików, dekoracyjnie ustawiona w kacie pokoju, przy ścianie, lub niszy gdzie zwierzęta są przetrzymywane w zamknięciu. Niestety jest to jeszcze do dnia dzisiejszego częsty obraz. Z naturalnymi potrzebami gatunku nie ma to nic wspólnego i każdy opiekun powinien zdawać sobie z tego sprawę, że taka klatkowa hodowla dla właściciela jest bardzo praktyczna, ale dla aktywnych i zdrowych królików jest katorga. Małe klatki nie mają na tyle miejsca, żeby królik mógł przeżyć cały swój repertuar naturalnych zachowań. Każdy królik potrzebuje \"norki\" do spania, w klatce musi być możliwość zejścia sobie z drogi, każdy królik powinien mieć swoje miejsce do odpoczynku. Do tego króliki są bardzo aktywnymi zwierzątkami, które chętnie biegają i kicają, zagroda powinna więc mieć dosyć miejsca, żeby uszak mógł wykonać jeden duży skok bez zagrożenia, że wyląduje na kracie klatki. Musi być oddzielne miejsce na jedzenie i oddzielne na toaletę. Sklepowe klatki tych warunków nie spełniają, mogą służyć jedynie jako miejsce przejściowe np. przy kwarantannie lub jako miejsce na odpoczynek w zagródce. Idealnie byłoby dla wszystkich królików gdyby mogły w dzień i w nocy biegać po całym mieszkaniu lub przynajmniej w jednym pokoju. Niestety nie zawsze jest to możliwe, duże zagrody z metalowych elementów są świetną alternatywą dla całodobowej wolności.</br>"
							+ "</br>" + "Wielkość</br>"
							+ "Na jednego królika przypada 2m² wybiegu większe rasy potrzebują 3m². Większość opiekunów będzie zaszokowana, 2m² na małe zwierzątko, dlaczego? Odpowiem obrazowo: w celi więziennej na jednego więźnia przypada łóżko, stół, krzesło, toaleta i umywalka. Teraz spójrzmy na normalnej wielkości klatkę: w kącie toaleta, jeśli królik ma szczęście to półka gdzie może sie umyć, niżej domek służący za łóżko, kąt na jedzenie i więcej nic sie nie zmieści. Więzień wychodzi ze swojej celi na kilka godzin na spacer. Króliki mają kilka godzin wybiegu. Co takiego zrobiły nasze zwierzęta, że są traktowane jak więźniowie? Czyż nie mają prawa jako nasi przyjaciele i współlokatorzy do naszego mieszkania? Króliki potrzebują przestrzeni gdzie zagospodarują swój wolny czas, muszą biegać, skakać, przytulać się i bawić. Do tego potrzeba 4m² dla dwóch uszaków. Każdy człowiek może wydzielić taki obszar ze swojego mieszkania. Wystarczy zrezygnować z kilku regałów,  stolika, poprzestawiać meble czy przegrodzić balkon. Tak, można, ale nie wszyscy ludzie są na to gotowi. Zadaje sobie pytanie: dlaczego więc trzymają swoje zwierzaki, miłość do zwierząt nie może być tu powodem.</br>"
							+ "</br>"
							+ "Króliki poruszają się do przodu kicając i skacząc. W zwykłej sklepowej klatce nie mogą wykonać jednego dużego skoku żeby nie wylądować na kracie, czy to jest zgodne z ich potrzebami? Często w książkach i organizacjach zwierzęcych poleca się klatkę o wymiarach 140 na 70 jako minimum dla dwóch królików, ale tylko dlatego, ponieważ większych klatek w sklepach nie ma. Jeśli ktoś musi mieć taką klatkę powinien połączyć dwie, (stawiając jedną na drugiej) oprócz tego pół dnia wybiegu to obowiązek. (...) Zupełnie nie nadają się klatki z plastikowa góra. Cyrkulacji powietrza prawie w niej nie ma, źle uchodzi gorąco i wilgoć. Akwarium też absolutnie się nie nadaje.</br>"
							+ "</br>" + "Zbudowane własnoręcznie</br>"
							+ "Świetnie nadają się zagrody zbudowane samemu, są tańsze i o wiele ładniejsze niż klatki. Przy wysokości 100cm góra może być otwarta, podłoga i 2-3 ściany ze sklejki, z przodu metalowa siatka, (lepsza cyrkulacja powietrza i oświetlenie) do tego drzwiczki żeby zwierzęta mogły same wychodzić i wchodzić kiedy chcą. Zrozumiałe, że nie każdy właściciel chce poświęcić swoje mieszkanie dla królików. W sklepach można znaleźć tanie zagródki z metalowych elementów, które można szybko rozłożyć i ustawić w dogodnym miejscu.</br>"
							+ "</br>"
							+ "Przy wyborze i urządzaniu zagródki warto przestrzegać pewnych zasad. Zagroda powinna chociaż w małej części zapewnić wszystkie możliwości naturalnego środowiska królika. W króliczym stadku panuje ścisła hierarchia. Każdy zwierzak potrzebuje miejsca do spania. Może to być duży domek, dolna część klatki z poleczka wyłożona słomą itp.</br>"
							+ "</br>"
							+ "Króliki o najwyższej pozycji w naturze zajmują norkę w środku rewiru. Nasze domowe zwierzęta często postępują tak samo. Dlatego w małych grupach króliczych domki/posłania powinny być ustawione na środku i na tylniej ścianie w bezpiecznym miejscu. Dla trzech zwierząt stawiamy dodatkowe posłania na brzegach aby niżej stojące w hierarchii króliki znalazły tam miejsce dla siebie. W kątach zagródki trzeba ustawić kuwety. Gdzie króliki będą chciały mięć swoje toalety wskażą państwu same. W oddali od kuwet stawiamy wodę i miseczki na pokarm. W zagródkach na dworze będą one stały w miejscu zadaszonym, w  mieszkaniu z dala od żwirku lub np. na pięterku.</br>"
							+ " </br>"
							+ "Paśniki i kąciki z sianem rozstawiamy w rożnych miejscach, szczególnie jednak w miejscach do odpoczynku. Część zagródki musi zapewnić miejsce do biegania i skakania, najlepiej do tego nadaje sie część przednia. Nie powinna ona być zastawiona zabawkami i innymi przedmiotami. Resztę miejsca przeznaczona jest do odkrywania, zabawy i szukania. Tu postawimy połówki rur, tunele i inne użytkowe przedmioty. Jeśli zagródka jest na to za mała, zabawki stawiamy na wybiegu. (...)"));

			firstBunnyService.create(new FirstBunny("Królik w klatce",
					"Zwierzęta, w tym również małe ssaki są kupowane przez ludzi, chcących się o nie troszczyć i dbać. Niestety w dużej mierze kupując zwierzę ludzie nie zdają sobie sprawy z ich wymagań. Szczególną popularnością w śród małych ssaków cieszą się króliki, które w przeciwieństwie do niektórych zwierząt w czasie głodu, strachu lub frustracji nie robią dużego hałasu, przez co są mniej uciążliwe dla opiekuna.</br>"
							+ "</br>"
							+ "Króliki są bardzo często kupowane przez dorosłych pod wpływem dzieci, które obiecują sumienne opiekowanie się zwierzęciem. Dzieci nie są skłonne w pełni zaopiekować się zwierzęciem, a do tego dochodzi jeszcze fakt, że wcześniejsze obietnice zostają szybko zapomniane i cały ciężar opieki spada na rodziców, którzy zazwyczaj nie mają czasu na opiekowanie się królikiem. W konsekwencji królik zostaje włożony do klatki, która zazwyczaj jest stawiana w odosobnionym miejscu np. garażu. Czasami dla koleżeństwa dodajemy drugiego królika do klatki, co może powodować sytuacje stresujące, szczególnie gdy jeden z osobników jest szczególnie dominujący, a królik zdominowany nie ma możliwości ucieczki. W konsekwencji królik spędza tak całe życie, które może trwać 13 lat. Opieka właściciela ogranicza się do podania jedzenia i picia, często nieświadomy właściciel nie wie nawet że królik jest chory i tak naprawdę pomału umiera w zamknięciu.</br>"
							+ "</br>"
							+ "Istnieje prawo, które mówi że zwierzęta gospodarcze, np. króliki trzymane na ubój muszą być codziennie badane w dobrym świetle, jak również muszą mieć codzienny dostęp do świeżej karmy, jak również picia. Chore osobniki muszą być odizolowane od reszty zwierząt. Jest to zapisane w ustawie o prawach zwierząt z 1911r.</br>"
							+ "</br>"
							+ "Bardzo ciężko jest stwierdzić prawdziwe zachowania królików, które są trzymane pojedynczo w klatkach. Dzikie króliki są bardzo towarzyskie, żyją w małych społecznościach, w których można zauważyć silny instynkt terytorialny. Ich układ trawienny jest przystosowany do spożywania wysoko włóknistej diety, w której niestrawne porcje są w szybki sposób wydalane, w postaci okrągłych bobków. Przyswajalny ułamek pokarmu jest zatrzymywany w jelicie ślepym i tam ulega fermentacji bakteryjnej, zanim zostanie wydalony w postaci małych kulek pokrytych śluzem i o silnym zapachu. Te kulki (cekotrofy) są dostarczycielem niezbędnych do prawidłowego funkcjonowania królika odżywek witaminowych. Proces, w którym powstają cekotrofy pozwala królikowi w szybki sposób przetrawić pokarm, co ma wpływ na szybszą ucieczkę do schronienia przed czyhającymi na nich drapieżnikami, jak również nieociężałość w czasie ucieczki. Twardy kał pełni role swoistego znacznika terytorium. Potrzeby fizjologiczne są głównym wyznacznikiem codziennego rytmu życia. Wzmożoną aktywność króliki wykazują późnym popołudniem i wczesnym rankiem, ten czas pożytkują na jedzenie, zabawę, znaczenie terenu i gody. Resztę dnia spędzają w swoich jamach, gdzie odpoczywają i budują wzajemne relacje społeczne. W szczególnie piękne dni króliki odpoczywają przed swoimi jamami, takiego zachowania nie zauważymy u samotnych królików, trzymanych w klatkach.</br>"
							+ "</br>"
							+ "W ostatnich latach warunki laboratoryjne uległy zmianie, został wdrążony plan trzymania królików bardziej zbliżony do naturalnych, tzn króliki nie są już trzymane w klatkach, a w większych pomieszczeniach i w większych grupach. Przeprowadzając tak badania tj. na królikach trzymanych pojedynczo w klatkach i na królikach w większych społecznościach naukowcy zauważyli zmiany morfologiczne w gruczołach nadnerczych między dwoma badanymi grupami, takie badania również dowiodły że króliki trzymane pojedynczo w klatkach mają mniejszą gęstość kości, co może prowadzić do deformacji kręgosłupa, szczególnie tyczy się to hodowanych tak samiczek. Takie \"dolegliwości\" są bardzo często spotykane u królików domowych, które mogą prowadzić do utraty elastyczności kręgosłupa, a co za tym idzie w znaczny sposób utrudniają, lub nawet uniemożliwiają spożywanie cekotrofów prosto z odbytu. Przy prawidłowym pobieraniu cekotrofów może również przeszkadzać dolegliwości związane z zębami, jak i otyłość królika. W klatkach takie </br>"
							+ "dolegliwości są bardzo uciążliwe dla królika, jak również dla jego opiekuna, szczególnie jeżeli chodzi o pielęgnację. Króliki w klatkach, które nie mogą pobierać cekotrofów prosto z odbytu są narażone na wiele problemów pielęgnacyjnych. W bardzo ograniczonej  przestrzeni wypadające cekotrofy nie są swobodnie pobierane, więc może się to skończyć przysiadaniem królika na swoich odchodach, a co za tym idzie tworzenia się kołtunów, w skład których wchodzić będzie sierść i cekotrofy. Zapach takiej mieszanki jest częstym powodem kolejnych następstw odosobnienia królika, które wraz z klatką są wynoszone w inne pomieszczenia, w których nieprzyjemny zapach nie doskwiera \"opiekunom\", lub są porzucane w inny sposób.</br>"
							+ "</br>"
							+ "Szczególną uwagę powinniśmy zwrócić na włóknistą dietę, której zaniedbania mogą prowadzić do</br>"
							+ " problemów gastrycznych, nieleczone są częstym powodem śmierci królika. Wiele królików kończy tak życie, zupełnie nieświadomych opiekunów. Stan, który uniemożliwia prawidłowemu pobieraniu cekotrofów, jest przyczyną chorób związanych z nieprawidłową pielęgnacją futra i skóry. Szczególnie częstymi pasożytami w takich problemach są Leporacus Gibbus i Cheyletiella parasitovorax (chejletieloza). Króliki trzymane w grupach nawzajem dbają o higienę w miejscach trudniej dostępnych. Osobniki trzymane pojedynczo, szczególnie ras długowłosych jak angory, nie są w stanie samotnie utrzymać higienę na przyzwoitym poziomie, a sytuacja ulega jeszcze pogorszeniu gdy doskwierają mu dolegliwości opisane powyżej. Bardzo otyłe samiczki mają dużo problemów z dbałością o higienę \"krocza\", gromadzą się tam różnego rodzaju nieczystości, zaniedbanie takich miejsc będzie prowadzić do zapaleń i zakażeń.</br>"
							+ "</br>"
							+ "Pododermatitis (schorzenie międzypalcowe) jest bardzo bolesnym stanem dla zwierzęcia, początek choroby zaczyna się właśnie u królików trzymanych w klatkach, gdzie podłoże jest mokre i brudne.</br>"
							+ " Konsekwencją takiego stanu będzie zagnieżdżenie się larw much, które mogą być przyczyną dalszych ułomności pielęgnacyjnych królika, co w końcu pogarsza jeszcze bardziej jego stan. Zarówno \"schorzenie międzypalcowe\" i larwy much jest często niezauważone przez opiekunów, aż do momentu znacznego pogorszenia stanu, taka sytuacja jest wyjątkowo częsta właśnie u zwierząt odizolowanych w innym pomieszczeniu niż pozostali domownicy. Na pogorszenie stanu zdrowia ma też wpływ nieodpowiednia dieta. Obecnie większość opiekunów swoją opiekę nad królikiem sprowadza do podania karmy. Kiedyś króliki były żywione kuchennymi karmami, plus pożywienie, które zdobyły same w ogrodzie takie jak trawa i inne zielska. Obecnie większość opiekunów kupuje karmę w sklepie, lub supermarkecie. Są zachęcani do karm składających się z dużej ilości zbóż, lub słodkich dodatków, wierząc że taka karma jest najlepsza dla naszych uszatych pupili. Mylące są również rady udzielane przez pracowników sklepowych, którzy nie mają pojęcia o potrzebach i wymaganiach królików. Powszechnym mitem jest że królik po zjedzeniu zieleniny może dostać biegunkę. Właściciele zwierząt, zachęcani przez reklamy, jak również swoją wygodę podają miskę lub dwie dziennie z taką mieszanką, która w znaczny sposób ogranicza spożycie siana, lub zieleniny. Taka dieta dostarcza bardzo mało składników mineralnych, niezmiernie ważnych do prawidłowego uzębienia i funkcjonowania królika. Niska zawartość włókna i wysoka węglowodanów sprawia że zmniejsza się fizjologiczne zapotrzebowanie na cekotrofy, ale również forma cekotrofów ulega przeinaczeniu. Cekotrofy zmieniają swoją formę na bardziej miękką, i kleistą, a w konsekwencji królik trzymany w klatce jest jeszcze bardziej narażony na kołtunie się sierści z cekotrofami. Takie karmowe mieszanki pozwalają królikowi na wybieranie ulubionych składników, są to szczególnie: kukurydza, groszek, pszenica, jest to dieta o bardzo małej zawartości wapna i witaminy D, przez co zęby, które rosną całe życie zostają pozbawione budulca, przez co dochodzi do szeregu schorzeń, jak również deformacji uzębienia. Problemy z korzeniami zębów, jak również z ich koroną sprawiają duży ból królikowi. Następstwami tych chorób mogą być ropnie, które utrudniają, lub wręcz uniemożliwiają spożywania pokarmów. Zboża wraz ze swoimi mieszankami, zawierają również bardzo małą ilość włókna, prowadzi to do poważnych problemów jak bezoary i owsiki w przewodzie pokarmowym. Króliki poddane diecie węglowodanowej</br>"
							+ " są narażone na otyłość i wszystkich problemów z tym związanych.</br>" + "</br>"
							+ "Podczas badań prowadzonych w latach 1995-1997, pobrano krew od królików z chorobami zębów. Stan krwi u królików \"wolno biegających\" był zupełnie inny niż królików zamkniętych w klatkach.</br>"
							+ "U królików chowanych bez klatkowo poziom krwinek czerwonych i białka był wyższy. Limfocyty nie były niskie tylko u chorych królików trzymanych w klatkach, ale również zaniżona wartość występowała u zdrowych \"więzionych\" osobników. W ostatniej dekadzie można zauważyć wzrost wiedzy na temat wymagań królika, przez co ich warunki bytowania w domach się poprawiły. Króliki nie są już tylko zachcianką dziecka, coraz więcej dorosłych ludzi wybiera te zwierzątka na domowego pupila zamiast psa czy kota, wpływ na to ma stosunkowo łatwiejsza pielęgnacja, szczególnie jeżeli jest mowa o wyjściach na spacer z psem. Nadal nader często spotykamy że króliki są zamykane w klatkach w czasie nieobecności domowników, lub są wypuszczane raz na kilka dni z klatki. Indywidualne cechy królików, jak również ciekawa natura sprawia że króliki są coraz częstszymi mieszkańcami w naszych domach. Są zwierzętami, które potrafią nawiązywać z człowiekiem bardzo silne wzajemne więzi. Kastracja (sterylizacja) zmieszają u królików zachowania niepożądane przez człowieka, przez co również są częściej wybierane na towarzyszy rodzinnych. Nowoczesne zakłady produkującą jedzenie, wypuszczają na rynek coraz więcej wysoko włóknistej karmy, które w połączeniu z zielenina i nieograniczonym dostępem do siana tworzą dietę niemal idealną. Świadomość społeczna jest coraz większa i przed zakupem przyszły właściciel zastanowi się nad swoim nabytkiem. Idealne życie królik wiedzie ze swoimi współtowarzyszami (czyt. inne króliki), w naszym ogrodzie z dala od drapieżników, gdzie mają nieograniczony dostęp do różnorakiej roślinności, kopią swoje jamy, jak również mają dużo miejsca do zabaw i pościgów. Takie warunki nie są jednak możliwe w większości domach, więc kompromisem jest zaopatrzyć się w dobrze usytuowaną klatkę o jak największych wymiarach, rozsądną dietę, codzienną dbałość o higienę klatki, jak również królika, zapewnienie królikowi dużo ruchu poza klatką, jak również współtowarzysza w postaci innego królika. "));

			firstBunnyService.create(new FirstBunny("Żaden królik nie zasługuje na samotność",
					"W naturze króliki żyją w dużych grupach i mają bardzo rozbudowane zachowania społeczne.</br>"
							+ "Tak jak ludzie potrzebują partnera, żeby być szczęśliwym.</br>"
							+ "Człowiek jest izolowany w celi za straszne czyny które popełnił.</br>"
							+ "Co zrobił królik, że trzeba go izolować?</br>"
							+ "Argumenty przeciwko trzymaniu królika w pojedynkę.</br>" + "</br>"
							+ "Większość opiekunów jednego królika ma przeważnie podobne argumenty za pojedynczym chowem. Najczęstsze i najbardziej przekonujące będą tu wymienione.</br>"
							+ "</br>" + "1. Mój królik czuje się szczęśliwy sam.</br>" + "</br>"
							+ "Króliki potrafią się świetnie przystosować. To, że królik był nieszczęśliwy widać dopiero po zaprzyjaźnieniu go z innym, jak bardzo się cieszy mając u boku partnera, jak odżył przy nowym przyjacielu. Czysto naukowo wszystko przemawia przeciwko szczęśliwemu życiu królika trzymanego w pojedynkę. Kto raz podpatrywał dzikie króliki, wie, że żyją one w dużych grupach. Mają bardzo rozwinięte zachowania społeczne: myją się wzajemnie, śpią obok siebie i bawią się razem. Także inne zachowania świadczą o stadnej naturze królika np. tupanie tylnymi skokami, które podczas zagrożenia ostrzega całą grupę. Według Ustawy o Ochronie zwierząt wszystkie zwierzęta powinny być chowane zgodnie ze swoja natura. Naturalne dla królika jest życie w grupie.</br>"
							+ "</br>" + "2. Bardzo dużo czasu poświęcam królikowi, rzadko jest sam.</br>" + "</br>"
							+ "Możesz go głaskać, ale nie lizać i myć. Możesz go karmić, ale nie sprzeczać się z nim o liść kalarepy. Możesz mu sianem wyścielić zagródkę, ale nie ogrzewać go w nocy, ale przede wszystkim możesz do niego mówić, ale nie jego mowa. Tego wszystkiego strasznie mu brakuje, nawet jeśli jesteś doskonałym opiekunem.</br>"
							+ "</br>" + "3. Mój królik nie jest sam, ma świnkę morska za partnera.</br>" + " </br>"
							+ "To jest jeden z gorszych tragizmowi dla królika, że ktoś wpadł na pomysł, że te dwa zwierzęta mogą być trzymane razem. Jeszcze gorszy dla świnki, która jest często dominowana i uciskana przez większego królika. Oczywiście \"rozumieją się\" czasami, ale jest to bardziej tolerancja niż przyjaźń. Oczywiście liżą się i leżą obok siebie, ale daj królikowi drugiego królika i świnkę do zagrody. Jak myślisz wybierze świnkę na swojego przyjaciela? Eksperyment pokazał: trzymana  grupa królików i grupa świnek w jednej zagrodzie, (żadne zwierze się wcześniej nie znało) podzieli się na dwie grupy, zgodnie ze swoim gatunkiem.</br>"
							+ "</br>" + "4. Nie mam miejsca na drugiego królika.</br>" + "</br>"
							+ "Tu jest inny temat poruszony, który przysparza być może tyle samo cierpienia królikowi co samotność. Wielkość klatki. Tak na prawdę to każdy kto kupuje królika chce dla niego jak najlepiej, dlatego kupuje dla niego \"dużą klatkę\" w sklepie zoologicznym. Niestety w sklepach nie ma dużych klatek. Wyliczono, że królik , który jest hodowany zgodnie z jego naturalnymi wymaganiami potrzebuje przynajmniej (!!!) 2 m2 dla siebie. Na podłodze byłoby to 2m x 1m. Uzasadnienie tego jest logiczne: Królik musi kicać, (to znaczy zrobić więcej niż trzy skoki) musi móc się wyciągnąć i przeciągnąć. Dwugodzinny wybieg nic nie daje jeśli przez 22 godziny królik siedzi w klatce 1,20 m na 0,6 m. Także króliczy dzień składa się z 24 godzin. Jeśli ktoś nie ma wystarczająco miejsca może zbudować kilku-poziomowa zagrodę. Dla dwóch królików powinno być zapewnione odpowiednio więcej miejsca.</br>"
							+ "</br>" + "5. Dwa króliki to dwa razy więcej pracy i dwa razy większe koszty.</br>"
							+ "</br>"
							+ "Drugi królik przysparza nam tylko minimalnie więcej pracy niż jeden. Przede wszystkim potrzebujemy więcej ściółki, jedzenia i miejsca. Za to nie musimy poświęcać królikowi tyle czasu bo ma już towarzystwo. Króliki mogą być bardzo drogie. Są choroby, które wymagają długiego leczenia, a co za tym idzie dużych kosztów, ale to trzeba wziąć pod uwagę przy kupnie pierwszego królika. Wiele chorób i zaburzeń w zachowaniu królika jest rezultatem  pojedynczego chowu. Drugi królik kosztuje może trochę więcej pieniędzy, ale jest to inwestycja w szczęście pierwszego uszaka, która się zwraca: Ty zapobiegasz zaburzeniom u swojego królika i pomagasz innemu (jeśli wziąłeś go np. ze schroniska) i masz dwa zwierzaki do kochania i obserwowania (co jest po prostu cudowne).</br>"
							+ "</br>" + "6. Chce żeby mój królik był oswojony.</br>" + "</br>"
							+ "Powszechna obawa jest, że przez towarzysza królik nie będzie taki przymilny. Z naszych doświadczeń wynika, że przez nowego partnera skraca się tylko czas, który królik spędzał sam. On ma kogoś do zabawy i jeśli wchodzimy do domu przybiegnie się przywitać nie tylko nasz jeden, ale obydwa naraz (trzy, cztery, pięć... :) ). U bojaźliwych królików partner sprawia, że są one odważniejsze, nadpobudliwe, staja się często spokojniejsze. Naturalnie nie jest się już tą najważniejszą osobą dla swojego królika, ale czy nie byłoby egoizmem oczekiwać tego od niego?</br>"
							+ "</br>" + "7. Mój królik jest za stary, żeby go przyzwyczajać do innego.</br>" + "</br>"
							+ "To jest w większości przypadków przekonanie opiekuna, a nie rzeczywistość. Prawdopodobnie wzięło się ono stąd, że królik np. podczas opieki nad innym królikiem, (w czasie wyjazdu właściciela) został na krótko wypuszczony na wybieg z przyjezdnym królikiem i doszło do przeganiania i pogryzień. Podczas takiego \"zapoznawania\" nie są przestrzegane żadne reguły dotyczące zaprzyjaźniania królików dlatego walki są normalne i wystąpiłyby u każdego królika. Opłaca się spróbować \"porządnie\", z dużą prawdopodobnością się powiedzie.</br>"
							+ "</br>" + "</br>"
							+ "Kto mimo wszystko się obawia, że na końcu zostanie z dwoma nielubiącymi się królikami może skorzystać ze schronisk, które chętnie dają króliki na próbę i w razie czego gdyby się nie zaprzyjaźniły można je z powrotem oddać. Ale jeszcze raz: jeśli przestrzega się wszystkich reguł zaprzyjaźniania, ma się cierpliwość, zwierzęta są przeciwnej płci i zapoznawane na neutralnym gruncie, musi się powieść !</br>"
							+ "</br>" + "Podsumowując:</br>"
							+ "Są przekonywujące argumenty za pojedynczym trzymaniem królika ?</br>"
							+ "My nie znamy żadnego.</br>"
							+ "Trzymanie królika samego jest jak więzienna izolacja człowieka!!!</br>"
							+ "Tekst napisany przez niemiecki odpowiednik Stowarzyszenia Pomocy Królikom (Kaninchenschutz). "));

			firstBunnyService.create(new FirstBunny("Porzucanie zwierząt",
					"Czas wakacyjno-urlopowy jest szczególny, nie tylko dla człowieka, ale również dla zwierząt, które w tym okresie zdecydowanie częściej są porzucane. W Polsce szacuje się, że od 12-15% zwiększa się porzucanie zwierząt właśnie w tym okresie. Nie dotyczy to tylko psów i kotów, (choć są w zdecydowanej większości) ale również są to króliki i inne. Z badań przeprowadzonych przez CBOS wynika że w ponad 54% polskich domów żyje jedno lub więcej zwierząt udomowionych. W roku 2003 zdecydowana większość badanych tj. około 72% deklarowało, że w czasie wyjazdów oddają zwierzęta pod opiekę kogoś z rodziny lub przyjaciół. Żaden z badanych nie przyznał się również co do porzucania zwierząt, ani do oddawania ich na czas urlopu do przechowalni. W roku ubiegłym tj. 2008 można zauważyć zdecydowany wzrost osób, które korzystają z hoteli dla zwierząt, jak dotąd nikt nie przeprowadził badań na temat tego wzrostu, ale po wypowiedziach samych właścicieli takich hoteli można wywnioskować, że tego typu działalność jest coraz bardziej potrzebna, szczególnie w czasie wakacji, jak również weekendów.</br>"
							+ "</br>"
							+ "W badaniach opinii publicznej na temat posiadania zwierząt, również znajdujemy, że zdecydowanie częściej trzymamy zwierzęta w gospodarstwach domowych, w których są dzieci do lat 18. Niektórzy uważają, że właśnie jednym z czynników porzucania zwierząt, jest nieodpowiedzialność dziecka wraz z jego rodzicami, tzn. gdy dziecku dane zwierze się znudzi, a rodzic nie ma czasu na opiekę nad nim, po prostu pozbywają się zwierzęcia w najmniej dla nich kłopotliwy sposób, czyli porzucenie w lesie, przywiązanie do płotu, lub wywiezienie w nieznane miejsce dla danego zwierzęcia, ewentualnie oddanie do schroniska. Takie sytuacje nasilają się szczególnie w czasie wakacji, gdy nie możemy zabrać ze sobą zwierząt, lub po prostu nie chcemy tego robić.</br>"
							+ "</br>"
							+ "Właściciele oddają zwierzęta do schronisk podają różne powody takiej decyzji m.in.:</br>"
							+ " - alergia dziecka,</br>" + " - brak czasu na opiekę,</br>"
							+ " - mniejsze mieszkanie,</br>" + " - gorsza sytuacja finansowa</br>" + " - agresja,</br>"
							+ " - niszczenie mieszkanie (tyczy się nieznajomości natury, co jest napisane poniżej),</br>"
							+ " - ciągłe szczekanie.</br>" + "</br>"
							+ "Około 30-35% zwierzaków jest oddawana osobiście przez właścicieli, którzy do tego się przyznają, ale osoby pracujące w schroniskach z racji doświadczenia uważają, że znacznie więcej zwierząt jest oddawanych przez właścicieli, którzy wstydzą się do tego przyznać.</br>"
							+ "W rzeczywistości powody porzucania zwierząt są bardziej złożone niż może się nam wydawać. Należy nadmienić że porzucanie zwierząt, jest prawnie uznane za znęcanie się (ustawa o ochronie zwierząt art. 6 ust.2 punkt 11.), czyli przestępstwem.</br>"
							+ "Najczęstsza przyczyna porzucania zwierząt jest pochopną decyzją i nieznajomość natury zwierzaka na jakiego się decydujemy.</br>"
							+ "Kolejnym z czynników, który powoduje wzrost liczebności porzuconych zwierząt są nielegalne hodowle, tyczy się to hodowli nie tylko psów, ale również kotów, królików, jak i innych mniej</br>"
							+ "lub bardziej popularnych zwierząt. Nielegalne hodowle są tylko i wyłącznie nastawione na finansowy zysk, co oznacza, że zupełnie nie zależy im na zwierzętach, jak również na ich jakości życia. Zwierzęta chore, niezdolne do reprodukcji, lub niesprzedające się są porzucane, oddawane do schronisk, lub uśmiercane.</br>"
							+ "Od dawna toczą się spory, czy zwykły klient, kupujący zwierzęta z takich hodowli nie wspomaga</br>"
							+ "tego biznesu. Oczywiście nie mówimy tutaj tylko o bezpośrednim kupowaniu zwierząt od właścicieli, ale również w sklepach zoologicznych, które \"zaopatrują się w towar\" właśnie w takich nielegalnych hodowlach, lub po prostu na targach. Wielu powie że wykupują zwierzęta ze sklepów, hodowli, targów aby poprawić im jakość życia, ale tak naprawdę nakręcają ten niehumanitarny biznes. Właściwszym wyjściem jest organizacja interwencji upoważnionych do tego celu organów.</br>"
							+ "</br>"
							+ "Kolejnym z powodów porzucania zwierząt, jest obecnie panująca moda, której w szczególnej mierze poddają się dzieci i nastolatki. Moda na daną rasę lub gatunek przemija, wraz z nią fascynacja, jak również ochota do opieki nad zwierzakiem, wtedy właśnie są podejmowane drastyczne kroki, które prowadzą właściciela do \"wyrzucenia\" zwierzęcia, bądź to w lesie, bądź do schroniska.</br>"
							+ "</br>"
							+ "Niekontrolowane rozmnażanie, jest kolejną przyczyną, która powoduje wzrost zwierząt które trafiają do schronisk. Każdy lubi małe, urocze stworzonka, ale gdy dorastają pojawia się problem co z nimi zrobić, najczęściej właśnie trafiają do schronisk. Kiedyś również popularna praktyką, szczególnie na wsiach było topienie małych zwierząt w rzekach i stawach.</br>"
							+ "</br>"
							+ "Do schronisk, również trafiają zwierzęta, które same uciekły od właścicieli. Przyczyny ucieczek są bardzo różne, od złego traktowania zwierzęcia, do zwykłej ucieczki, która jest spowodowana instynktem (chęć wolności), lub popędami.</br>"
							+ "</br>"
							+ "Zanim zdecydujemy się na zwierzę, nie bierzmy pod uwagę tylko jego wyglądu, ale jeszcze przed zakupem zapoznajmy się z naturą zwierzaka i wymaganiami. Pamiętajmy również że króliki mogą dożyć do 13 lat, koty do 20, podobnie jak psy, nie wspominając o papugach, które potrafią żyć tyle samo co człowiek. Powinniśmy sobie uświadamiać fakt, że przez taki okres mamy zajmować się danym zwierzęciem, które bardzo się do nas przywiązuje i każde rozstanie jest dla niego bardzo nieprzyjemnym przeżyciem.</br>"
							+ "</br>"
							+ "Zwierzęta pozostawione w domu przez dłuższy czas bez opieki, potrafią narobić szkód z nudów, dlatego aby uniknąć problemów i rozczarowań zapewnijmy im w czasie naszej nieobecności zabawki, tak aby pupilowi uprzyjemnić rozstania z nami, a nam pozwoli to zminimalizować ewentualne szkody. "));

		};
	}
}
